name: ci
on:
  pull_request:
  push:
    branches:
      - main


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - 1.56
          - stable
    steps:
      - name: Setup | Checkout repository
        uses: actions/checkout@v3
      - name: Setup | Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Setup | Cache rust
        uses: Swatinem/rust-cache@v2
      - name: Run | Run cargo test
        run: cargo test
  fmt:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout repository
        uses: actions/checkout@v3
      - name: Setup | Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Check | Formatting
        run: cargo fmt --all -- --check
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout repository
        uses: actions/checkout@v3
      - name: Setup | Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Setup | Cache rust
        uses: Swatinem/rust-cache@v2
      - name: Check | Run clippy
        run: cargo clippy --tests -- -D warnings
